---
- name: Docker
  hosts: all
  become: yes
  tasks:
    - name: Install apt prerequisites for Docker installation
      apt: "name={{ item }} update_cache=yes"
      with_items:
        - apt-transport-https
        - ca-certificates

    - name: Add apt-key for docker repository
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com
        id: 58118E89F3A912897C070ADBF76221572C52609D

    - name: Add docker repository for Ubuntu Xenial
      apt_repository:
        repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main

    - name: Create configuration directory
      file: path=/etc/systemd/system/docker.service.d state=directory

    - name: Install docker
      apt: "name={{ item }} update_cache=yes"
      with_items:
        - "linux-image-extra-{{ ansible_kernel }}"
        - linux-image-extra-virtual
        - docker-engine

    - name: Update docker configuration
      copy:
        src: ansible-files/docker.conf
        dest: /etc/systemd/system/docker.service.d/docker.conf
      notify:
        - Restart Docker


    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.9.0/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: a+x

  handlers:
    - name: Restart Docker
      systemd: name=docker state=restarted daemon_reload=yes